# Generated by Django 5.0.6 on 2024-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoinheritance', '0002_examcenter_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CopyProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangoinheritance.product',),
        ),
    ]
