# Generated by Django 5.0.6 on 2024-05-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoinheritance', '0003_product_copyproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copyproduct',
            options={'ordering': ['id']},
        ),
    ]
